### ISSUE TITLE
Update for Nyxt 2-pre-release-7

### ISSUE THREAD

**Issue by Ambrevar** [aartaka/nx-search-engines#1]
`nyxt::generate-search-query` is gone upstream.
@aartaka Any idea how to fix this package to run on the upcoming 2-pre-release-7?

**Comment by aartaka** [comment]
I'll look into it!

**Comment by aartaka** [comment]
Done with a3aeeab1a59c8f088b4bc5210bc5e994c086a6a3!

**Comment by Ambrevar** [comment]
Thanks a lot!
