### ISSUE TITLE
Nyxt 2.x support clarification

### ISSUE THREAD

**Issue by hendursaga** [aartaka/nx-search-engines#10]
Now that the first pre-release of the 3.x series is out, is there going to be any support for the 2.x series in the future? (Not that I mind personally) At any rate the docs should be updated to at least include 3.x changes, such as no `load-after-system`, etc.

**Comment by aartaka** [comment]
I'll update the docs, thanks for reminding me of that!

I plan to support 2.x, as it should be relatively easy.
