### ISSUE TITLE
Fix mountain of style warnings

### ISSUE THREAD

**Issue by hendursaga** [aartaka/nx-search-engines#11]
With the `define-search-engine` macro, I get a wall of warnings like...

```
; caught STYLE-WARNING:
;   The variable FORCE-SUPPLY-P is defined but never used.

; in: DEFINE-SEARCH-ENGINE HACKER-NEWS
```

Perhaps adding ignorable declarations would help? Or &optional instead of &key??

**Comment by aartaka** [comment]
Indeed, those have been cluttering my Nyxt shell output for a while! Time to fix those :D
