### ISSUE TITLE
Add a generic or base search engine

### ISSUE THREAD

**Issue by ghost** [aartaka/nx-search-engines#14]
Upon wanting to add more basic search engines, I realized that this could quickly get out of hand and this project would end up with too many engines. Now, since a user can easily define an engine in their configuration, would it be worth it to add a new `engines:base-search-engine` or `engines:generic-engine` so the user could override its basic arguments as follows?

``` common-lisp
(engines:generic-engine
 :shortcut "my"
 :fallback-url (quri:uri "https://example.com")
 :base-search-url "https://example.com/q?=~a")
```

**Comment by aartaka** [comment]
Note that there already is `nyxt:make-search-engine` that does exactly that:
``` lisp
;; Creates a search engine with the shortcut, base-search-url, and fallback-url (respectively).
(nyxt:make-search-engine "my" "https://example.com/q?=~a" "https://example.com")
```
It's even mentioned in the manual, so I don't see much improvement required here.

What would make this extension much easier to use is the graphical menu for search engine selection -- this way we don't even need the README. The syntax of `define-search-engine` is easily parseable and it should be possible to generate an HTML form out of it. It's just that someone needs to write this interface code xD

**Comment by ghost** [comment]
You're right, with all this abstraction I completely forgot about `nyxt:make-search-engine`. An internal page describing the engines would indeed be ideal!
