### ISSUE TITLE
Add Brave Search

### ISSUE THREAD

**Issue by pyrox0** [aartaka/nx-search-engines#8]
Could you add the brave search engine(at https://search.brave.com/)? It's the one I use as my school blocks DuckDuckGo for some reason.

**Comment by aartaka** [comment]
I can, but the timeframe is uncertain :)

As you know Brave Search much better than I do, you might actually be more competent in implementing it. The `define-search-engine` macro is more or less understandable in basic things, you can try copy-pasting and playing with it in Nyxt. 

If you don't feel like it, I will add Brave in a week or so.

**Comment by pyrox0** [comment]
Sounds great! Thanks for the quick response! My lisp skills aren't that great, but I'll try! :P

**Comment by aartaka** [comment]
Feel free to ping me here in case something is not obvious ;)

**Comment by aartaka** [comment]
@ModdedGamers I've added Brave suport in 98cfe77bda21ebbc3ea1933ef4862eb1418572be. I hope it's not too late :D

**Comment by pyrox0** [comment]
Woo!
Edit: I did switch to another search engine, but I want to try to add that one myself. Good first thing to write in Lisp.

**Comment by aartaka** [comment]
> Woo!
> Edit: I did switch to another search engine, but I want to try to add that one myself. Good first thing to write in Lisp.

No problem, will be glad to see your PR :)
